#!/usr/bin/env python3
"""
Generate UCSDPascal/PMachineTables.inc -- the P-machine DATA that P-Code mode
needs from the Z80 interpreter file SYSTEM.MICRO, so that P-Code mode (with
register compatibility off and reclaimed memory) needs neither SYSTEM.MICRO
nor pascal.bin. No Z80 code is copied: only tables.

    python3 make_pmachine_tables.py <boot disk .BLK> <output .inc>

Everything is taken from the file exactly as the pascal.bin loader places it
(the image is found at 0400h and moved to 0100h, i.e. address a is file
offset a - 0x0100 + 0x0300), before the interpreter's BOOT code runs.
"""
import sys
D = 1024
def w(b, o): return b[o] | (b[o + 1] << 8)
def entries(img):
    for i in range(1, w(img, D + 16) + 1):
        o = D + 26 * i
        yield dict(first=w(img, o), last=w(img, o + 2), name=bytes(img[o + 7:o + 7 + img[o + 6]]).decode('latin1'))
img = bytearray(open(sys.argv[1], 'rb').read())
e = next(x for x in entries(img) if x['name'] == 'SYSTEM.MICRO')
micro = img[e['first'] * 512:e['last'] * 512]
off = 0x0300 - 0x0100 if micro[0] != 0x2D else -0x0100
def at(a): return micro[a + off]
def rng(a, n): return bytes(at(a + i) for i in range(n))
rb = lambda a: at(a & 0xFFFF)
rw = lambda a: rb(a) | (rb(a + 1) << 8)
# unit-I/O configuration: the same discovery as PmIoConfigFromImage (PCodeOpcodes.h)
uw = rw(0x15E7 + 2 * 37); assert rb(uw) == 0x3E and rb(uw + 5) == 0xCD
getu = rw(uw + 6); assert rb(getu) == 0xAF and rb(getu + 11) == 0xFE and rb(getu + 24) == 0x11
maxu1 = rb(getu + 12); unitbl = rw(getu + 25)
flags = [0] * 16; kind = [0] * 16; civ = [0] * 16; cov = [0] * 16; syeof = 0
for u in range(1, maxu1):
    upt = (unitbl + ((u * 4) & 0xFF)) & 0xFFFF
    flags[u] = rb(upt); d = rw(upt + 2); a = [rb(d + k) for k in range(6)]
    if a[:5] == [0x3A, 0xD3, 0x02, 0xD3, 0xC8]: kind[u] = 1; continue
    if a[:5] == [0x3A, 0xD2, 0x02, 0xE6, 0x04] and a[5] in (0xCA, 0xC2):
        c12 = a[5] == 0xCA; common = rw(d + 6) if c12 else d + 8
        if rb(common) != 0xCD or rb(common + 0x2C) != 0x3A: continue
        setvect = rw(common + 1)
        if rb(setvect + 6) != 0x11: continue
        ctable = rw(setvect + 7)
        kind[u] = 2 if c12 else 3; civ[u] = rb(ctable + 2 * u); cov[u] = rb(ctable + 2 * u + 1); syeof = rw(common + 0x2D)
def arr(name, data, comment):
    body = ',\n'.join('    ' + ', '.join('0x%02X' % b for b in data[i:i + 16]) for i in range(0, len(data), 16))
    return f"// {comment}\nstatic const uint8_t {name}[{len(data)}] = {{\n{body}\n}};\n"
out = ["""// PMachineTables.inc -- GENERATED by tools/make_pmachine_tables.py from the
// SYSTEM.MICRO on the boot disk. Do not edit by hand.
//
// The P-machine DATA the native engine needs when P-Code mode runs without
// SYSTEM.MICRO (register compatibility off, reclaimed memory). No Z80 code:
// the opcode dispatch table's entries are only used as handler identifiers.
// Each table lives at its address in the Z80 interpreter's layout inside the
// engine's private table copy (m_rom), where PM_ROM reads it.
""",
 arr("kPmXfrtbl", rng(0x0100, 0x100), "0x0100: opcode dispatch table (XFRTBL), opcodes 80H-FFH"),
 arr("kPmVarInit", rng(0x0200, 0x01A4), "0x0200-0x03A3: the P-machine variables, SYSCOM, SEGTBL -- initial values"),
 arr("kPmTentbl", rng(0x0FF7, 39 * 4), "0x0FF7: powers of ten 10^0..10^38 (POT)"),
 arr("kPmRestbl", rng(0x1766, 0x1994 - 0x1766), "0x1766: reserved words (IDSEARCH): 27-entry letter index + 42 records of 12 bytes"),
 arr("kPmCxp02", rng(0x03D7, 3), "0x03D7: the P-code instruction CXP 0,2 (call EXECERROR), for run-time errors"),
 arr("kPmSystle", rng(0x1ECC, 14), "0x1ECC: the operating system's file name (length byte, SYSTEM.PASCAL)"),
 f"""// The unit-I/O configuration (PmIoConfig): units 1..{maxu1 - 1}; kinds 1 = Big Disk,
// 2 = console character units (1, 2), 3 = other character units (6, 7, 8).
static PmIoConfig BuiltInIoConfig() {{
    PmIoConfig c;
    c.ok = true; c.maxu1 = {maxu1}; c.unitbl = 0x{unitbl:04X}; c.syeof = 0x{syeof:04X};
    static const uint8_t f[16] = {{ {', '.join('0x%02X' % x for x in flags)} }};
    static const uint8_t k[16] = {{ {', '.join(str(x) for x in kind)} }};
    static const uint8_t ci[16] = {{ {', '.join('0x%02X' % x for x in civ)} }};
    static const uint8_t co[16] = {{ {', '.join('0x%02X' % x for x in cov)} }};
    for (int u = 0; u < 16; u++) {{ c.flags[u] = f[u]; c.kind[u] = k[u]; c.civ[u] = ci[u]; c.cov[u] = co[u]; }}
    return c;
}}
"""]
open(sys.argv[2], 'w').write('\n'.join(out))
print(f"{sys.argv[2]}: XFRTBL 256, variables 420, TENTBL 156, RESTBL {0x1994 - 0x1766}, CXP02 3, SYSTLE 14 bytes; "
      f"units 1..{maxu1 - 1}: kinds {kind[1:maxu1]}, SYEOF {syeof:04X}")
