PROGRAM BATCH2TEST;
VAR I, J: INTEGER;
BEGIN
I := -7; WRITELN('ABS(-7)=', ABS(I));
I := 5; J := 3;
IF I = J THEN WRITELN('5=3 TRUE') ELSE WRITELN('5=3 FALSE');
IF I <> J THEN WRITELN('5<>3 TRUE') ELSE WRITELN('5<>3 FALSE');
IF I >= J THEN WRITELN('5>=3 TRUE') ELSE WRITELN('5>=3 FALSE');
IF I > J THEN WRITELN('5>3 TRUE') ELSE WRITELN('5>3 FALSE');
IF I <= J THEN WRITELN('5<=3 TRUE') ELSE WRITELN('5<=3 FALSE');
IF I < J THEN WRITELN('5<3 TRUE') ELSE WRITELN('5<3 FALSE');
IF TRUE AND FALSE THEN WRITELN('TANDF TRUE') ELSE WRITELN('TANDF FALSE');
IF TRUE OR FALSE THEN WRITELN('TORF TRUE') ELSE WRITELN('TORF FALSE');
END.
