PROGRAM CLEANUPTEST;
TYPE SMALLRANGE = 1..10;
VAR X: SMALLRANGE; Y: REAL; I: INTEGER;
BEGIN
I := 5; X := I; WRITELN('X=',X);
Y := 0.5;
WRITELN(SIN(Y));
WRITELN(SQRT(2.0));
I := 15; X := I;
WRITELN('SHOULD NOT REACH');
END.
