PROGRAM BATCH5TEST;
TYPE SMALLINT = 0..3;
     PACKEDARR = PACKED ARRAY[1..8] OF SMALLINT;
VAR I, J: INTEGER;
    PA: PACKEDARR;
    K: INTEGER;
BEGIN
I := 123; J := 456;
WRITELN('123 * 456 = ', I * J);
I := -17; J := 23;
WRITELN('-17 * 23 = ', I * J);
FOR K := 1 TO 8 DO PA[K] := K MOD 4;
FOR K := 1 TO 8 DO WRITE(PA[K], ' ');
WRITELN;
PA[3] := 2; PA[7] := 1;
FOR K := 1 TO 8 DO WRITE(PA[K], ' ');
WRITELN;
END.
