PROGRAM BATCH6TEST;
VAR S, T: STRING[20];
    N, K: INTEGER;
    ST: SET OF 0..63;
FUNCTION FACT(X: INTEGER): INTEGER;
BEGIN
  IF X <= 1 THEN FACT := 1 ELSE FACT := X * FACT(X - 1)
END;
PROCEDURE OUTER(A: INTEGER);
  VAR B: INTEGER;
  PROCEDURE INNER(C: INTEGER);
  BEGIN
    B := B + C + A;
    WRITELN('INNER B=', B)
  END;
BEGIN
  B := 100;
  INNER(5);
  INNER(7)
END;
BEGIN
WRITELN('FACT(7)=', FACT(7));
OUTER(10);
S := 'ALPHA'; T := 'ALPHA';
IF S = T THEN WRITELN('S=T') ELSE WRITELN('S<>T');
T := 'ALPHB';
IF S <> T THEN WRITELN('S<>T NOW') ELSE WRITELN('STILL EQUAL');
IF S < T THEN WRITELN('ALPHA<ALPHB') ELSE WRITELN('WRONG ORDER');
N := 3; K := 9;
ST := [N..K];
IF 5 IN ST THEN WRITELN('5 IN [3..9]') ELSE WRITELN('5 MISSING');
IF 10 IN ST THEN WRITELN('10 WRONGLY IN') ELSE WRITELN('10 NOT IN [3..9]');
ST := [N];
IF 3 IN ST THEN WRITELN('3 IN [3]') ELSE WRITELN('3 MISSING');
END.
