PROGRAM BATCH4TEST;
TYPE COLOR = (RED, GREEN, BLUE, YELLOW);
VAR S1, S2: SET OF COLOR;
    I, J: INTEGER;
    C: COLOR;
BEGIN
S1 := [RED, GREEN, BLUE];
S2 := [GREEN, BLUE];
IF GREEN IN S1 THEN WRITELN('GREEN IN S1') ELSE WRITELN('NOT IN S1');
IF YELLOW IN S1 THEN WRITELN('YELLOW IN S1') ELSE WRITELN('YELLOW NOT IN S1');
I := 17; J := 5;
WRITELN('17 DIV 5 = ', I DIV J);
WRITELN('17 MOD 5 = ', I MOD J);
I := -17;
WRITELN('-17 DIV 5 = ', I DIV J);
WRITELN('-17 MOD 5 = ', I MOD J);
FOR C := RED TO YELLOW DO
  CASE C OF
    RED: WRITELN('case: RED');
    GREEN: WRITELN('case: GREEN');
    BLUE: WRITELN('case: BLUE');
    YELLOW: WRITELN('case: YELLOW');
  END;
END.
